import type { Trip, TripSortKey, TripStatus } from "@/types/trip";
import type { VehicleType } from "@/types/vehicle";

// ─── Filter & Sort Options ─────────────────────────────────────────────────────

export type TripFilterOption<TValue extends string = string> = {
  label: string;
  value: TValue;
};

export const tripStatusOptions: TripFilterOption<"All" | TripStatus>[] = [
  { label: "All", value: "All" },
  { label: "Draft", value: "Draft" },
  { label: "Dispatched", value: "Dispatched" },
  { label: "Completed", value: "Completed" },
  { label: "Cancelled", value: "Cancelled" },
];

export const tripVehicleTypeOptions: TripFilterOption<"All" | VehicleType>[] = [
  { label: "All", value: "All" },
  { label: "Truck", value: "Truck" },
  { label: "Van", value: "Van" },
  { label: "Mini Truck", value: "Mini Truck" },
];

export const tripSortOptions: TripFilterOption<TripSortKey>[] = [
  { label: "Latest", value: "Latest" },
  { label: "Oldest", value: "Oldest" },
  { label: "Longest Distance", value: "Longest Distance" },
];

// ─── Mock Data ─────────────────────────────────────────────────────────────────

export const mockTrips: Trip[] = [
  {
    id: "trip-1",
    tripId: "TR001",
    source: "Raipur",
    destination: "Nagpur",
    vehicleId: "vehicle-1",
    vehicleName: "Van-05",
    vehicleType: "Van",
    driverId: "driver-1",
    driverName: "Alex Johnson",
    cargoWeight: 450,
    plannedDistance: 285,
    status: "Completed",
    expectedStartDate: "2026-07-01",
    expectedDeliveryDate: "2026-07-02",
    notes: "Fragile electronics — handle with care.",
    createdAt: "2026-07-01T06:00:00.000Z",
    dispatchedAt: "2026-07-01T08:30:00.000Z",
    completedAt: "2026-07-02T14:00:00.000Z",
    cancelledAt: null,
    finalOdometer: 42785,
    fuelUsed: 32,
    deliveryNotes: "Delivered in good condition.",
    timeline: [
      { type: "created", label: "Trip Created", timestamp: "2026-07-01T06:00:00.000Z" },
      { type: "vehicle_assigned", label: "Vehicle Assigned", timestamp: "2026-07-01T06:05:00.000Z" },
      { type: "driver_assigned", label: "Driver Assigned", timestamp: "2026-07-01T06:10:00.000Z" },
      { type: "dispatched", label: "Dispatched", timestamp: "2026-07-01T08:30:00.000Z" },
      { type: "reached", label: "Reached Destination", timestamp: "2026-07-02T13:45:00.000Z" },
      { type: "completed", label: "Completed", timestamp: "2026-07-02T14:00:00.000Z" },
    ],
  },
  {
    id: "trip-2",
    tripId: "TR002",
    source: "Raipur",
    destination: "Bilaspur",
    vehicleId: "vehicle-2",
    vehicleName: "Truck-01",
    vehicleType: "Truck",
    driverId: "driver-2",
    driverName: "John Smith",
    cargoWeight: 800,
    plannedDistance: 130,
    status: "Dispatched",
    expectedStartDate: "2026-07-10",
    expectedDeliveryDate: "2026-07-10",
    notes: "Construction materials.",
    createdAt: "2026-07-10T07:00:00.000Z",
    dispatchedAt: "2026-07-10T09:00:00.000Z",
    completedAt: null,
    cancelledAt: null,
    finalOdometer: null,
    fuelUsed: null,
    deliveryNotes: "",
    timeline: [
      { type: "created", label: "Trip Created", timestamp: "2026-07-10T07:00:00.000Z" },
      { type: "vehicle_assigned", label: "Vehicle Assigned", timestamp: "2026-07-10T07:05:00.000Z" },
      { type: "driver_assigned", label: "Driver Assigned", timestamp: "2026-07-10T07:10:00.000Z" },
      { type: "dispatched", label: "Dispatched", timestamp: "2026-07-10T09:00:00.000Z" },
      { type: "reached", label: "Reached Destination", timestamp: null },
      { type: "completed", label: "Completed", timestamp: null },
    ],
  },
  {
    id: "trip-3",
    tripId: "TR003",
    source: "Raipur",
    destination: "Durg",
    vehicleId: "vehicle-3",
    vehicleName: "Mini-03",
    vehicleType: "Mini Truck",
    driverId: "driver-1",
    driverName: "Alex Johnson",
    cargoWeight: 250,
    plannedDistance: 42,
    status: "Draft",
    expectedStartDate: "2026-07-12",
    expectedDeliveryDate: "2026-07-12",
    notes: "",
    createdAt: "2026-07-12T05:00:00.000Z",
    dispatchedAt: null,
    completedAt: null,
    cancelledAt: null,
    finalOdometer: null,
    fuelUsed: null,
    deliveryNotes: "",
    timeline: [
      { type: "created", label: "Trip Created", timestamp: "2026-07-12T05:00:00.000Z" },
      { type: "vehicle_assigned", label: "Vehicle Assigned", timestamp: "2026-07-12T05:02:00.000Z" },
      { type: "driver_assigned", label: "Driver Assigned", timestamp: "2026-07-12T05:03:00.000Z" },
      { type: "dispatched", label: "Dispatched", timestamp: null },
      { type: "reached", label: "Reached Destination", timestamp: null },
      { type: "completed", label: "Completed", timestamp: null },
    ],
  },
  {
    id: "trip-4",
    tripId: "TR004",
    source: "Nagpur",
    destination: "Mumbai",
    vehicleId: "vehicle-1",
    vehicleName: "Van-05",
    vehicleType: "Van",
    driverId: "driver-1",
    driverName: "Alex Johnson",
    cargoWeight: 320,
    plannedDistance: 840,
    status: "Cancelled",
    expectedStartDate: "2026-07-05",
    expectedDeliveryDate: "2026-07-06",
    notes: "High-value cargo — requires signed receipt.",
    createdAt: "2026-07-05T08:00:00.000Z",
    dispatchedAt: null,
    completedAt: null,
    cancelledAt: "2026-07-05T10:00:00.000Z",
    finalOdometer: null,
    fuelUsed: null,
    deliveryNotes: "",
    timeline: [
      { type: "created", label: "Trip Created", timestamp: "2026-07-05T08:00:00.000Z" },
      { type: "vehicle_assigned", label: "Vehicle Assigned", timestamp: "2026-07-05T08:05:00.000Z" },
      { type: "driver_assigned", label: "Driver Assigned", timestamp: "2026-07-05T08:10:00.000Z" },
      { type: "dispatched", label: "Dispatched", timestamp: null },
      { type: "reached", label: "Reached Destination", timestamp: null },
      { type: "completed", label: "Completed", timestamp: null },
    ],
  },
  {
    id: "trip-5",
    tripId: "TR005",
    source: "Bhopal",
    destination: "Indore",
    vehicleId: "vehicle-2",
    vehicleName: "Truck-01",
    vehicleType: "Truck",
    driverId: "driver-2",
    driverName: "John Smith",
    cargoWeight: 1200,
    plannedDistance: 195,
    status: "Completed",
    expectedStartDate: "2026-06-28",
    expectedDeliveryDate: "2026-06-29",
    notes: "Cement bags.",
    createdAt: "2026-06-28T06:30:00.000Z",
    dispatchedAt: "2026-06-28T08:00:00.000Z",
    completedAt: "2026-06-29T11:30:00.000Z",
    cancelledAt: null,
    finalOdometer: 98195,
    fuelUsed: 45,
    deliveryNotes: "2 bags damaged en route.",
    timeline: [
      { type: "created", label: "Trip Created", timestamp: "2026-06-28T06:30:00.000Z" },
      { type: "vehicle_assigned", label: "Vehicle Assigned", timestamp: "2026-06-28T06:35:00.000Z" },
      { type: "driver_assigned", label: "Driver Assigned", timestamp: "2026-06-28T06:40:00.000Z" },
      { type: "dispatched", label: "Dispatched", timestamp: "2026-06-28T08:00:00.000Z" },
      { type: "reached", label: "Reached Destination", timestamp: "2026-06-29T11:00:00.000Z" },
      { type: "completed", label: "Completed", timestamp: "2026-06-29T11:30:00.000Z" },
    ],
  },
  {
    id: "trip-6",
    tripId: "TR006",
    source: "Jabalpur",
    destination: "Raipur",
    vehicleId: "vehicle-3",
    vehicleName: "Mini-03",
    vehicleType: "Mini Truck",
    driverId: "driver-1",
    driverName: "Alex Johnson",
    cargoWeight: 180,
    plannedDistance: 300,
    status: "Draft",
    expectedStartDate: "2026-07-14",
    expectedDeliveryDate: "2026-07-14",
    notes: "Medical supplies.",
    createdAt: "2026-07-12T09:00:00.000Z",
    dispatchedAt: null,
    completedAt: null,
    cancelledAt: null,
    finalOdometer: null,
    fuelUsed: null,
    deliveryNotes: "",
    timeline: [
      { type: "created", label: "Trip Created", timestamp: "2026-07-12T09:00:00.000Z" },
      { type: "vehicle_assigned", label: "Vehicle Assigned", timestamp: "2026-07-12T09:02:00.000Z" },
      { type: "driver_assigned", label: "Driver Assigned", timestamp: "2026-07-12T09:03:00.000Z" },
      { type: "dispatched", label: "Dispatched", timestamp: null },
      { type: "reached", label: "Reached Destination", timestamp: null },
      { type: "completed", label: "Completed", timestamp: null },
    ],
  },
];
